### ISSUE TITLE
New repos failing key checking

### ISSUE THREAD

**Issue by edgard** [alanfranz/docker-rpm-builder#12]
Something seems funky trying to use the new repos from fedora21.

I added both keys and still getting problem authenticating the packages:

https://packagecloud.io/alanfranz/docker-rpm-builder-v1/fedora/21/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for docker-rpm-builder-v1

**Comment by alanfranz** [comment]
Hello, thanks for your report. I'm checking this out tonight.
Il 09/apr/2015 18:18, "Edgard Castro" notifications@github.com ha scritto:

**Comment by alanfranz** [comment]
I got the multiple gpgkey config wrong; The fix to the README has just been committed. Just remove the _gpgkey=_ part of the second line, leaving the rest of the line as it is.

**Comment by edgard** [comment]
Works, perfect! Thanks! :+1:
