### ISSUE TITLE
RHEL 6 1.14 RPM is empty, does not install application

### ISSUE THREAD

**Issue by jhenry82** [alanfranz/docker-rpm-builder#13]
There seems to be a problem with the version 1.14 RPM for RHEL/CentOS 6. The file is tiny, and does not actually install the application. It created a completely empty directory tree under /opt/docker-rpm-builder/.

```
# ls -l /opt/docker-rpm-builder/bin
total 0
#docker-rpm-builder selftest
bash: docker-rpm-builder: command not found
# yum list installed docker-rpm-builder
Loaded plugins: fastestmirror, security
Installed Packages
docker-rpm-builder.x86_64                                 1.14-build98                                 @alanfranz_docker-rpm-builder-v1
```

Could you please check on these RPM's, and generate new ones if necessary? Thanks.

**Comment by jhenry82** [comment]
Slight clarification: that dir is leftover from the old 1.7 version I was attempting to upgrade. The 1.14 RPM actually does even less. It just creates a symlink to that dir under /opt, which on a fresh install doesn't even exist.

```
# ls -l /usr/bin/docker-rpm-builder
lrwxrwxrwx 1 root root 46 Apr 22 10:22 /usr/bin/docker-rpm-builder -> /opt/docker-rpm-builder/bin/docker-rpm-builder
# ls -l /opt/docker-rpm-builder/bin/docker-rpm-builder
ls: cannot access /opt/docker-rpm-builder/bin/docker-rpm-builder: No such file or directory
```

**Comment by alanfranz** [comment]
Hello,
Sorry for the issue. I'll check it out asap, but it'll probably take me a
couple of days since I'm on vacation until sunday.
Il 22/apr/2015 18:34, "Jon Henry" notifications@github.com ha scritto:

**Comment by alanfranz** [comment]
Hello,
I don't know what actually happened, but the package I've just uploaded should be ok.

I'll change the repositories again in the near future, so please stay tuned and check the readme if the packagecloud repo fails to work in the future.

Thanks for your report.

**Comment by alanfranz** [comment]
Feel free to open another ticket if you find other problems or if the issue persists.
