### ISSUE TITLE
RHEL7 $releasever is 7server so, repos are "broken"

### ISSUE THREAD

**Issue by e-minguez** [alanfranz/docker-rpm-builder#15]
Adding the docker-rpm-builder.repo file to RHEL7 doesn't point to the proper URL.
In RHEL7, the $releasever variable is "7Server":

```
yum-debug-dump version 1
%%%%SYSTEM INFO
  uname: 3.10.0-229.7.2.el7.x86_64, x86_64
  rpm ver: RPM version 4.11.1
  python ver: 2.7.5 (default, Apr  9 2015, 11:03:32) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
%%%%YUM INFO
  arch: ia32e
  basearch: x86_64
  releasever: 7Server
  yum ver: 3.4.3
  enabled plugins: product-id
  global excludes: 
```

And the repo only has the "7" folder. I think you can create a symlink in the repository to support both releasever variables.

**Comment by alanfranz** [comment]
Hello, I'm checking this immediately... I think then that Centos7 is
different? Can you confirm?

**Comment by e-minguez** [comment]
CentOS output:

```
yum-debug-dump version 1
%%%%SYSTEM INFO
  uname: 3.10.0-229.4.2.el7.x86_64, x86_64
  rpm ver: RPM version 4.11.1
  python ver: 2.7.5 (default, Jun 17 2014, 18:11:42) [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
%%%%YUM INFO
  arch: amd64
  basearch: x86_64
  releasever: 7
  yum ver: 3.4.3
  enabled plugins: fastestmirror,langpacks
  global excludes: 
```

**Comment by alanfranz** [comment]
Thank you, I've verified the issue. I didn't know that there were "official" rhel (not centos) docker images around.

It should be fixed by now, I've created a proper symlink. Try and let me know.

Also: if you find anything that I should add to the documentation for installing docker-rpm-builder on official RHEL (I've always tested just centos) please let me know.

**Comment by e-minguez** [comment]
Official docker images are located here -> https://access.redhat.com/search/#/container-images (you'll need a proper subscription to get them. To access Red Hat products, you can register in http://developers.redhat.com/)

Speaking about the issue, I can confirm it is working now:

```
$ grep baseurl /etc/yum.repos.d/docker-rpm-builder.repo 
baseurl=http://www.a9f.eu/yum/docker-rpm-builder-v1/centos/$releasever/$basearch/

$ yum update
Loaded plugins: product-id, subscription-manager
...
docker-rpm-builder-v1/7Server/x86_64/signature                                                                                                                                                                         |  473 B  00:00:00     
docker-rpm-builder-v1/7Server/x86_64/signature                                                                                                                                                                         | 2.9 kB  00:00:00 !!! 
No packages marked for update

```

Thanks
