### ISSUE TITLE
Ubuntu package depends on non-existent package 'docker-engine'

### ISSUE THREAD

**Issue by nocnokneo** [alanfranz/docker-rpm-builder#16]
Following the installation instructions for Ubuntu 15.04 (vivid), I get the following error when I run to `apt-get install docker-rpm-builder`

```
The following packages have unmet dependencies:
 docker-rpm-builder : Depends: docker-engine (>= 1.8) but it is not installable
```

As far as I can tell, that package does not exist:

http://packages.ubuntu.com/search?suite=all&searchon=names&keywords=docker-engine

**Comment by alanfranz** [comment]
Hello,
take a look at the [Prerequisites](https://github.com/alanfranz/docker-rpm-builder#prerequisites) section.

The package depends on the latest official docker-engine deb. Check the official Docker Installation instructions: 

https://docs.docker.com/engine/installation/ubuntulinux/
