### ISSUE TITLE
Latest Centos7 package in the repo is not signed

### ISSUE THREAD

**Issue by cjbnc** [alanfranz/docker-rpm-builder#17]
rpm -Kv docker-rpm-builder-1.24-27.x86_64.rpm 
docker-rpm-builder-1.24-27.x86_64.rpm:
    Header SHA1 digest: OK (b91a24fc45714feaa19786d57dc092b2e1c2e0b0)
    MD5 digest: OK (3427bd1e8a274d3ee520a805d115234f)

**Comment by aframachines** [comment]
Sorry for the issue. I'm checking for what happened tomorrow.

**Comment by alanfranz** [comment]
I've checked right now, actually. OK, when moving to the new fpm-based packaging system I just forgot to enable signing. I'll release 1.25 tomorrow along with a small fix that I'm developing.

Thanks for your attention.

**Comment by alanfranz** [comment]
Hello, 1.25 was released, and it's properly signed. There's still a little change I'd like to do soon, as well as to document a new feature, so probably 1.26 will be out in the next few days. 

Thanks for your report.
