### ISSUE TITLE
Additions for Makefile

### ISSUE THREAD

**Issue by knighcl** [alanfranz/docker-rpm-builder#2]
Hello,

I made a concept to download git sources and do full rpm builds within containers for the freeipa project. I made changes to your general scripts to do it similarly. The changes were to support Makefiles and to download sources from git into the container. Would you like a pull request for enhancements?

Do you think you might do docker-rpm-builder-configurations for Fedora20/21/rawhide?

Thanks,
Curtis

**Comment by alanfranz** [comment]
Hello,
I'm sorry for the long time it took me to address this, but the tool needed quite an heavy refactor to be usable.

Now it is, and there're prebuilt images for f20/f21/rawhide as well. I hope it's useful to you!
