### ISSUE TITLE
missing path on server for yum repo

### ISSUE THREAD

**Issue by dansou901** [alanfranz/docker-rpm-builder#28]
Hi @alanfranz,  
I just found out that you are referencing to $releasever in your repofile for RHEL-like systems. However, on your server the respective piece of the path is named 7Server, which I believe will only work for RHEL itself, but not for CentOS or for example Oracle Linux. There, the path would have to be just .../7/x86_64. So I would suggest that you create a symlink from 7 to 7Server to get that solved as well.  
And to support SL, you can also do a symlink from 7.2 to 7 (you'll have to that everytime a new minor release of SL is published).  
Regards,
dansou901

**Comment by aframachines** [comment]
7, 7Client and 7Server, all of those exist and work. Which path are you
missing, exactly?

About SL: the 7.2 fix works now. But when 7.3 is out, I need to add another
one. It's too complex and I don't care - the documentation already tells SL
users what to do.

**Comment by dansou901** [comment]
Hi @aframachines, I'm sorry for the late reply. Seems like Oracle Linux does the same as SL when it comes to using subreleases in $releasever. So this is closed, I didn't pay attention. Thanks anyway!
Regards,
dansou901
