### ISSUE TITLE
Release RPM for Fedora 24

### ISSUE THREAD

**Issue by thefotios** [alanfranz/docker-rpm-builder#29]
Would it be possible to release an RPM for F24? I noticed you committed some configs for it a week ago.

I also noticed that https://yum.dockerproject.org/repo/main/fedora/24 doesn't exist (yet?). Are you getting around that somehow?

EDIT: This is where you're using the F24 docker repo, but not sure how/if that's even working https://github.com/alanfranz/docker-rpm-builder/blob/v1dev/packaging/fedora-24/test-inside-rc/test#L9

**Comment by alanfranz** [comment]
Yes, sure. I had some issues with fpm-within-docker (the tool I use to
create the RPM for docker-rpm-builder), but I hope to release for fc24 very
soon.

**Comment by alanfranz** [comment]
@thefotios there seems to be no official docker client for fedora 24 yet:

http://yum.dockerproject.org/repo/main/fedora/

could you tell me which version of docker is available in fc24 repos? and what's the name of the package?

**Comment by alanfranz** [comment]
Hello @thefotios , I tried testing docker-rpm-builder with the latest docker-engine 1.2rc5, but it's got a bug preventing the tests to complete.

docker 1.12 is behind the corner, I'll release a version of docker-rpm-builder for fc24 as soon as it's out.

**Comment by thefotios** [comment]
Actually, I started looking into that and they released `docker-engine@1.12.0` today.

**Comment by alanfranz** [comment]
Hello,
docker-rpm-builder v1.32 was just released. thanks for your patience.

**Comment by thefotios** [comment]
Thanks! And thanks for the awesome project.
