### ISSUE TITLE
Fedora 24 RPM fails

### ISSUE THREAD

**Issue by jchristi** [alanfranz/docker-rpm-builder#30]
In Fedora 24, the docker package is now called `docker` (not docker-engine). The F24 RPM still depends on a `docker-engine` package though.

**Comment by alanfranz** [comment]
From the README:

```
So, docker >= 1.11 is currently a prerequisite. If you're using the prebuilt RPMs or DEBs, they expect the docker-engine package from yum.dockerproject.org or apt.dockerproject.org to be available; just follow the official install instructions.
```

The docker-rpm-builder prebuilt package ALWAYS expects the latest version of docker-engine from the official repos. I don't have the time nor the will to support every and each different version of docker which may come with distributions - most get quickly out of date by the way (FC24 has 1.10 while the latest is 1.12)

If you'd like to use the distro package, please install docker-rpm-builder from source.
