### ISSUE TITLE
Chainbuild: support creating a .src.rpm and building from that

### ISSUE THREAD

**Issue by alanfranz** [alanfranz/docker-rpm-builder#35]
More than once somebody has asked a way to output a .src.rpm as well as a binary rpm. Building "a source rpm as well as a binary" is a complex task, because we want builds to be reproducible.

This task can normally by accomplished with an ```rpmbuild -bs``` on the host system, command that just creates a source rpm, but people seem to find it useful to get everything in one shot.

What can be done is to add another command, I'll call it **chainbuild**, that, first thing, creates a .src.rpm, then builds a binary rpm from it; it wouldn't be as fast as the **dir** command, but while the former would be used for "production builds", the latter would retain its usefulness for development.

I'll try to keep the semantics as close as possibile as **dir**; basically, a source rpm will be created with the full contents of the source dir, then such source rpm will be used to build a binary package.

Potential issues:
 * the caller must be either be sure to clean the source directory before calling **chainbuild** or to specify the proper exclusion patterns, otherwise the .tar.gz could grow excessively large and/or contain futile artifacts
 * speed may be compromised.

**Comment by iav** [comment]
Yes, seems good, and limitations are reasonable.
It will be comfortable to use "old build style" for debugging of a build package, and then to use special slow mode to get final release.

**Comment by alanfranz** [comment]
Version 1.35 sports the 'chainbuild' command. It's not the most polished piece of code I've written in my life, but it should do the trick. Test it out.

**Comment by iav** [comment]
Nice!
Will try during nearest week.

**Comment by iav** [comment]
Trying to build latest version of docker-rpm-builder fail on rinning build in ~/docker-rpm-builder/packaging/centos-7:
I need to pass proxy url and login/password to access to internet, without it 
docker build --pull -t docker-rpm-builder-centos-7-build build-image
fails on yum -y install python wget ca-certificates

I try to ann http_proxy var into docker-rpm-builder/packaging/env.list,
and add  --env "http_proxy=..." into docker run line on docker-rpm-builder/packaging/centos-7/build
but without success.

**Comment by alanfranz** [comment]
this has nothing to do with this ticket, right?
also, you seem to be doing random things. specify http_proxy (and export) before the docker build, not the docker run.

**Comment by alanfranz** [comment]
why don't you pick a prebuilt package, btw?

**Comment by iav** [comment]
> why don't you pick a prebuilt package, btw?

Because I first install it with yum repo and forgot about "releases" section in github.
Sorry. Now will use it.

**Comment by iav** [comment]
Now I made builds with docker-rpm-builder-1.36-build172.centos7.x86_64.rpm.
All works like a charm!

Thank you very much!!!

**Comment by alanfranz** [comment]
Great!
