### ISSUE TITLE
Request: package for Fedora 25

### ISSUE THREAD

**Issue by pkgw** [alanfranz/docker-rpm-builder#36]
Fedora 25 has been released, so it would be nice for a new RPM package of the project to be built.

**Comment by alanfranz** [comment]
Sure. I got some issues with the build of some RPM based distros when trying to enable the builtin docker packages, still fixing those issues; I think I'll issue a new release with fc25 support within a couple of weeks.

**Comment by alanfranz** [comment]
hello,
It took me a bit to complete the transition to bintray. Now the fc25 package is available on the new repos.
