### ISSUE TITLE
Concurrent docker-rpm-builder not working because dockerscripts volume mount options

### ISSUE THREAD

**Issue by mvazquezc** [alanfranz/docker-rpm-builder#44]
When running multiple instances of docker-rpm-builder in the same machine, only one instance finish successfully because the dockerscripts volume is mounted with private unshared label (Z) instead of shared label (z).

If you mount the dockerscripts volume with Z one container has access to the files inside the directory while the others get a Permission denied error.

Mounting this volume with z works fine.

If you require any further information, let me know.

**Comment by alanfranz** [comment]
I admit I'm not a SELinux expert. It was @pkgw that contributed that change; Peter, what do you think?

**Comment by pkgw** [comment]
I think the report is spot-on. Just a capitalization change from `Z` to `z` should fix the problem, and I don't think there are any downsides.

**Comment by alanfranz** [comment]
OK, thanks @pkgw and @mvazquezc . I'm doing a new release shortly.

**Comment by alanfranz** [comment]
docker-rpm-builder 1.39 is out, with the SELinux fix and spec directory override support.
