### ISSUE TITLE
RPM builds failing when trying to write something to SOURCES directory

### ISSUE THREAD

**Issue by mvazquezc** [alanfranz/docker-rpm-builder#45]
In some of our RPMs we perform some steps in the preparation section that unzip files, create directories, etc...

The problem here is that SOURCES dir is mounted in read only by default and the rpmbuild script fails with permission denied errors.

Changing the line 159 of dir.py and mounting SOURCES as rw it works fine:
`.bindmount_dir(source_directory, sources_inner_dir, read_only=False)`

What do you think about changing the default behaviour or providing an argument to docker-rpm-builder to control wether to mount SOURCES directory as RO or RW?

Thank you,

**Comment by alanfranz** [comment]
Uhm,
that's intentional, because otherwise you could end up with a modified (or even deleted) copy of the SOURCES directory.

By the way, it is highly unusual to write something to the SOURCES directory; usually things are unpacked to the build directory.

Can I have an example of your specfile?

**Comment by mvazquezc** [comment]
Hi @alanfranz,

The spec code:
`%prep
gzip -dc ${current_dir}/../SOURCES/%{app_sources_file} | tar -xvvf -
`
Reading the rpm building standards I haven't found anything regarding unpacking things in SOURCES, so it seems is a common practice to unpack things in BUILD as you said.

That said, we're going to change our spec file in order to be as standard as possible.

From my side this issue can be closed. 

Thank you for your time.
