### ISSUE TITLE
Compatibility with python 3

### ISSUE THREAD

**Issue by kduret** [alanfranz/docker-rpm-builder#49]
Hi,

I am not able to install docker-rpm-builder on Ubuntu artful.
Is it planned to add compatibility with python 3 ?

Regards

**Comment by alanfranz** [comment]
I don't think that I'll add python3 compatibility. But I plan to release an updated version which contains artful packages within the month. Artful does offer python2.7 packages.

**Comment by alanfranz** [comment]
https://github.com/alanfranz/docker-rpm-builder/issues/51

**Comment by alanfranz** [comment]
Consider becoming a docker-rpm-builder developer: https://github.com/alanfranz/docker-rpm-builder/issues/51

**Comment by alanfranz** [comment]
@kduret version 1.41 with artful support has been released.
