### ISSUE TITLE
Fedora 27 Support

### ISSUE THREAD

**Issue by mjmjelde** [alanfranz/docker-rpm-builder#50]
Fedora 27 was released back in November.  Any plans on support it?

**Comment by alanfranz** [comment]
I have, but I'm quite busy lately. I'll put out a "call for maintainers" soon, I can't think to keep supporting this piece of software alone.

**Comment by alanfranz** [comment]
If you can contribute a PR in the meantime, I'll surely take a look at it.

**Comment by alanfranz** [comment]
https://github.com/alanfranz/docker-rpm-builder/issues/51

**Comment by alanfranz** [comment]
version 1.41 with fc27 support is out.
