### ISSUE TITLE
--download-sources errors when no external sources

### ISSUE THREAD

**Issue by mgriffin13** [alanfranz/docker-rpm-builder#55]
I'm trying to migrate and use this tool for our battery of RPMs, but we have a mix of local and remote sources. Rather than attempting to determine which need the ``--download-sources`` option, I would rather just pass it to every build. Currently, though, the ``--download-sources`` functionality fails the build if it doesn't find any remote sources to download.

As a crude workaround, I simply patched ``downloadsources.py`` with this:

```python
+++ downloadsources.py  2018-02-08 11:23:27.225586000 -0500
@@ -45,6 +45,9 @@

     lines = get_spec_with_resolved_macros(specfilename, target_image)
     urls = get_source_and_patches_urls(lines)
+    if not urls:
+        _logger.debug("No sources to download")
+        return
     download_files(urls, source_directory)

 def get_spec_with_resolved_macros(specfilename, target_image):
```

**Comment by alanfranz** [comment]
Thanks for your interest. I'm still trying to find collaborators; please stay tuned.
