### ISSUE TITLE
ocker-rpm-builder dir --download-sources alanfranz/drb-epel-7-x86-64:latest . /tmp/rpms failed

### ISSUE THREAD

**Issue by wxg10000** [alanfranz/docker-rpm-builder#58]
...
Installed:
  libevent-devel.x86_64 0:2.0.21-4.el7
  ncurses-devel.x86_64 0:5.9-14.20130511.el7_4

Dependency Installed:
  libevent.x86_64 0:2.0.21-4.el7

Complete!
[2018-08-14T12:49:34+0000] INFO [rpmbuild-dir-in-docker.sh] Download of build dependencies succeeded
[2018-08-14T12:49:34+0000] INFO [rpmbuild-dir-in-docker.sh] Now executing rpmbuild; this could take a while...
[2018-08-14T12:49:34+0000] INFO [rpmbuild-dir-in-docker.sh] rpmbuild command failed:output is: -->
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.mIlRAh
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cp -pr /root/rpmbuild/SOURCES/tmux .
cp: cannot stat '/root/rpmbuild/SOURCES/tmux': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.mIlRAh (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.mIlRAh (%prep)
rpmbuild command output end

.
[2018-08-14T12:49:34+0000] INFO [rpmbuild-dir-in-docker.sh] Finished. Outcome: FAIL

**** FULL OUTPUT END ****
[2018-08-14T20:49:35+0800] ERROR [UserExceptionTransformer] Full catched exception:
Traceback (most recent call last):
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/commands/dir.py", line 168, in dir
    docker.do_launch_interactively()
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/docker.py", line 71, in do_launch_interactively
    self._run(fds={"stdout":1, "stderr":2, "stdin":0})
  File "/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/docker.py", line 95, in _run
    raise SpawnedProcessError(retcode, fullcmd, output=output, error=error)
SpawnedProcessError: Command '/usr/bin/docker run --init --rm --volume=/root/rpmbuild/SPECS/tmux.spec:/root/rpmbuild/SPECS/tmux.spec:z,ro --volume=/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/dockerscripts:/dockerscripts:z,ro --volume=/root/rpmbuild/SPECS:/root/rpmbuild/SOURCES:z,ro --volume=/tmp/rpms:/root/rpmbuild/RPMS:z --workdir=/dockerscripts --env=CALLING_UID=0 --env=CALLING_GID=0 --env=BASH_ON_FAIL='' --volume=/tmp/drb-temp.EyRvgf:/tmp:z alanfranz/drb-epel-7-x86-64:latest ./rpmbuild-dir-in-docker.sh' returned non-zero exit status 1:
None
None

Error: docker run error
Command '/usr/bin/docker run --init --rm --volume=/root/rpmbuild/SPECS/tmux.spec:/root/rpmbuild/SPECS/tmux.spec:z,ro --volume=/opt/docker-rpm-builder/lib/python2.7/site-packages/drb/dockerscripts:/dockerscripts:z,ro --volume=/root/rpmbuild/SPECS:/root/rpmbuild/SOURCES:z,ro --volume=/tmp/rpms:/root/rpmbuild/RPMS:z --workdir=/dockerscripts --env=CALLING_UID=0 --env=CALLING_GID=0 --env=BASH_ON_FAIL='' --volume=/tmp/drb-temp.EyRvgf:/tmp:z alanfranz/drb-epel-7-x86-64:latest ./rpmbuild-dir-in-docker.sh' returned non-zero exit status 1:
None
None

Build error. See the log above

Looking forward to your help, thanks!

**Comment by aframachines** [comment]
Please post the command that you are trying to run.

**Comment by wxg10000** [comment]
@aframachines  I am honored to receive your reply.
Running this command is successful and you can see the docker image.
docker-rpm-builder selftest --full
But it failed when I ran this command. Add tmux.spec to the current directory and report the errors I sent you.
docker-rpm-builder dir --download-sources alanfranz/drb-epel-5-x86-64:latest . /tmp/rpms

The tmux.spec  refers to docker-rpm-builder/example/from_dir/tmux.spectemplate.
