### ISSUE TITLE
Problem with centos repo

### ISSUE THREAD

**Issue by Seitanas** [alanfranz/docker-rpm-builder#60]
Hello,
since today docker-rpm-builder centos repo is failing:

```
 yum -q -y makecache --disablerepo=* --enablerepo=docker-rpm-builder-v1
http://dl.bintray.com/alanfranz/drb-v1-centos-7/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo docker-rpm-builder-v1
Trying other mirror.
```

**Comment by alanfranz** [comment]
I have a TLS issue with my website (www.franzoni.eu), the keys are fetched from there. I don't know why but Let's Encrypt renewal failed. I should solve this within a few hours; sorry for the inconvenience.

**Comment by alanfranz** [comment]
now everything should be ok.
